# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://infranets.github.io/
title: infraNets
email: o.gregoire07@gmail.com
author: infraNets

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
 # - title: facebook
  #  url: https://www.facebook.com/infranets/?ref=br_rs#
 # - title: github#
  #  url: https://github.com/orgs/infranETS/ #
